/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package dk.itu.pervasive.common.test;

public final class R {
    public static final class anim {
        public static final int login_button_out=0x7f030000;
        public static final int login_fields_animation=0x7f030001;
        public static final int logout_button_out=0x7f030002;
    }
    public static final class attr {
        /** 
    The size of the ad. It must be one of BANNER, FULL_BANNER, LEADERBOARD,
    MEDIUM_RECTANGLE, SMART_BANNER, WIDE_SKYSCRAPER, or
    &lt;width&gt;x&lt;height&gt;.
        
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int adSize=0x7f010000;
        /** 
    A comma-separated list of the supported ad sizes. The sizes must be one of
    BANNER, FULL_BANNER, LEADERBOARD, MEDIUM_RECTANGLE, SMART_BANNER,
    WIDE_SKYSCRAPER, or &lt;width&gt;x&lt;height&gt;.
        
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int adSizes=0x7f010001;
        /**  The ad unit ID. 
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int adUnitId=0x7f010002;
        /**  Appearance of the buy button. Must be one of "classic", "grayscale" and "monochrome" 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>classic</code></td><td>1</td><td></td></tr>
<tr><td><code>grayscale</code></td><td>2</td><td></td></tr>
<tr><td><code>monochrome</code></td><td>3</td><td></td></tr>
</table>
         */
        public static final int buyButtonAppearance=0x7f010018;
        /** 
             Height of the buy button. This includes an 8dp padding (4dp on each side) used for
             pressed and focused states of the button. The value can be a specific height, e.g.
             "48dp", or special values "match_parent" and "wrap_content".
        
         <p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>match_parent</code></td><td>-1</td><td></td></tr>
<tr><td><code>wrap_content</code></td><td>-2</td><td></td></tr>
</table>
         */
        public static final int buyButtonHeight=0x7f010015;
        /**  Text on the buy button. Must be one of "buy_with_google", "buy_now" and "book_now" 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>buy_with_google</code></td><td>1</td><td></td></tr>
<tr><td><code>buy_now</code></td><td>2</td><td></td></tr>
<tr><td><code>book_now</code></td><td>3</td><td></td></tr>
</table>
         */
        public static final int buyButtonText=0x7f010017;
        /** 
             Width of the buy button. This includes an 8dp padding (4dp on each side) used for
             pressed and focused states of the button. The value can be a specific width, e.g.
             "300dp", or special values "match_parent" and "wrap_content".
        
         <p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>match_parent</code></td><td>-1</td><td></td></tr>
<tr><td><code>wrap_content</code></td><td>-2</td><td></td></tr>
</table>
         */
        public static final int buyButtonWidth=0x7f010016;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraBearing=0x7f010004;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTargetLat=0x7f010005;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTargetLng=0x7f010006;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTilt=0x7f010007;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraZoom=0x7f010008;
        /**  Google Wallet environment to use 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>production</code></td><td>1</td><td></td></tr>
<tr><td><code>sandbox</code></td><td>0</td><td></td></tr>
<tr><td><code>strict_sandbox</code></td><td>2</td><td></td></tr>
</table>
         */
        public static final int environment=0x7f010012;
        /**  Fragment mode 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>buyButton</code></td><td>1</td><td></td></tr>
<tr><td><code>selectionDetails</code></td><td>2</td><td></td></tr>
</table>
         */
        public static final int fragmentMode=0x7f010014;
        /**  A style resource specifing attributes to customize the look and feel of WalletFragment 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int fragmentStyle=0x7f010013;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>normal</code></td><td>1</td><td></td></tr>
<tr><td><code>satellite</code></td><td>2</td><td></td></tr>
<tr><td><code>terrain</code></td><td>3</td><td></td></tr>
<tr><td><code>hybrid</code></td><td>4</td><td></td></tr>
</table>
         */
        public static final int mapType=0x7f010003;
        /**  Masked wallet details background 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int maskedWalletDetailsBackground=0x7f01001b;
        /**  "Change" button background in masked wallet details view 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int maskedWalletDetailsButtonBackground=0x7f01001d;
        /**  TextAppearance for the "Change" button in masked wallet details view 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int maskedWalletDetailsButtonTextAppearance=0x7f01001c;
        /**  TextAppearance for headers describing masked wallet details 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int maskedWalletDetailsHeaderTextAppearance=0x7f01001a;
        /**  Type of the wallet logo image in masked wallet details view 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>classic</code></td><td>1</td><td></td></tr>
<tr><td><code>monochrome</code></td><td>2</td><td></td></tr>
</table>
         */
        public static final int maskedWalletDetailsLogoImageType=0x7f01001f;
        /**  Color of the Google Wallet logo text in masked wallet details view 
         <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int maskedWalletDetailsLogoTextColor=0x7f01001e;
        /**  TextAppearance for masked wallet details 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int maskedWalletDetailsTextAppearance=0x7f010019;
        /**  Theme to be used for the Wallet selector 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>holo_dark</code></td><td>0</td><td></td></tr>
<tr><td><code>holo_light</code></td><td>1</td><td></td></tr>
</table>
         */
        public static final int theme=0x7f010011;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiCompass=0x7f010009;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiRotateGestures=0x7f01000a;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiScrollGestures=0x7f01000b;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiTiltGestures=0x7f01000c;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiZoomControls=0x7f01000d;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiZoomGestures=0x7f01000e;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int useViewLifecycle=0x7f01000f;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int zOrderOnTop=0x7f010010;
    }
    public static final class color {
        public static final int common_action_bar_splitter=0x7f040000;
        public static final int common_signin_btn_dark_text_default=0x7f040001;
        public static final int common_signin_btn_dark_text_disabled=0x7f040002;
        public static final int common_signin_btn_dark_text_focused=0x7f040003;
        public static final int common_signin_btn_dark_text_pressed=0x7f040004;
        public static final int common_signin_btn_default_background=0x7f040005;
        public static final int common_signin_btn_light_text_default=0x7f040006;
        public static final int common_signin_btn_light_text_disabled=0x7f040007;
        public static final int common_signin_btn_light_text_focused=0x7f040008;
        public static final int common_signin_btn_light_text_pressed=0x7f040009;
        public static final int common_signin_btn_text_dark=0x7f040017;
        public static final int common_signin_btn_text_light=0x7f040018;
        public static final int wallet_bright_foreground_disabled_holo_light=0x7f04000a;
        public static final int wallet_bright_foreground_holo_dark=0x7f04000b;
        public static final int wallet_bright_foreground_holo_light=0x7f04000c;
        public static final int wallet_dim_foreground_disabled_holo_dark=0x7f04000d;
        public static final int wallet_dim_foreground_holo_dark=0x7f04000e;
        public static final int wallet_dim_foreground_inverse_disabled_holo_dark=0x7f04000f;
        public static final int wallet_dim_foreground_inverse_holo_dark=0x7f040010;
        public static final int wallet_highlighted_text_holo_dark=0x7f040011;
        public static final int wallet_highlighted_text_holo_light=0x7f040012;
        public static final int wallet_hint_foreground_holo_dark=0x7f040013;
        public static final int wallet_hint_foreground_holo_light=0x7f040014;
        public static final int wallet_holo_blue_light=0x7f040015;
        public static final int wallet_link_text_light=0x7f040016;
        public static final int wallet_primary_text_holo_light=0x7f040019;
        public static final int wallet_secondary_text_holo_dark=0x7f04001a;
    }
    public static final class drawable {
        public static final int action_bar_bg_green=0x7f020000;
        public static final int available=0x7f020001;
        public static final int common_signin_btn_icon_dark=0x7f020002;
        public static final int common_signin_btn_icon_disabled_dark=0x7f020003;
        public static final int common_signin_btn_icon_disabled_focus_dark=0x7f020004;
        public static final int common_signin_btn_icon_disabled_focus_light=0x7f020005;
        public static final int common_signin_btn_icon_disabled_light=0x7f020006;
        public static final int common_signin_btn_icon_focus_dark=0x7f020007;
        public static final int common_signin_btn_icon_focus_light=0x7f020008;
        public static final int common_signin_btn_icon_light=0x7f020009;
        public static final int common_signin_btn_icon_normal_dark=0x7f02000a;
        public static final int common_signin_btn_icon_normal_light=0x7f02000b;
        public static final int common_signin_btn_icon_pressed_dark=0x7f02000c;
        public static final int common_signin_btn_icon_pressed_light=0x7f02000d;
        public static final int common_signin_btn_text_dark=0x7f02000e;
        public static final int common_signin_btn_text_disabled_dark=0x7f02000f;
        public static final int common_signin_btn_text_disabled_focus_dark=0x7f020010;
        public static final int common_signin_btn_text_disabled_focus_light=0x7f020011;
        public static final int common_signin_btn_text_disabled_light=0x7f020012;
        public static final int common_signin_btn_text_focus_dark=0x7f020013;
        public static final int common_signin_btn_text_focus_light=0x7f020014;
        public static final int common_signin_btn_text_light=0x7f020015;
        public static final int common_signin_btn_text_normal_dark=0x7f020016;
        public static final int common_signin_btn_text_normal_light=0x7f020017;
        public static final int common_signin_btn_text_pressed_dark=0x7f020018;
        public static final int common_signin_btn_text_pressed_light=0x7f020019;
        public static final int do_not_disturb=0x7f02001a;
        public static final int ic_launcher=0x7f02001b;
        public static final int ic_plusone_medium_off_client=0x7f02001c;
        public static final int ic_plusone_small_off_client=0x7f02001d;
        public static final int ic_plusone_standard_off_client=0x7f02001e;
        public static final int ic_plusone_tall_off_client=0x7f02001f;
        public static final int powered_by_google_dark=0x7f020020;
        public static final int powered_by_google_light=0x7f020021;
    }
    public static final class id {
        public static final int book_now=0x7f050010;
        public static final int buyButton=0x7f05000a;
        public static final int buy_now=0x7f05000f;
        public static final int buy_with_google=0x7f05000e;
        public static final int classic=0x7f050011;
        public static final int grayscale=0x7f050012;
        public static final int holo_dark=0x7f050005;
        public static final int holo_light=0x7f050006;
        public static final int hybrid=0x7f050004;
        public static final int match_parent=0x7f05000c;
        public static final int monochrome=0x7f050013;
        public static final int none=0x7f050000;
        public static final int normal=0x7f050001;
        public static final int production=0x7f050007;
        public static final int sandbox=0x7f050008;
        public static final int satellite=0x7f050002;
        public static final int selectionDetails=0x7f05000b;
        public static final int strict_sandbox=0x7f050009;
        public static final int terrain=0x7f050003;
        public static final int wrap_content=0x7f05000d;
    }
    public static final class integer {
        public static final int google_play_services_version=0x7f060000;
    }
    public static final class string {
        public static final int accelerometer_notification=0x7f070000;
        public static final int accelerometer_notification_text=0x7f070001;
        public static final int accelerometer_notification_title=0x7f070002;
        public static final int action_profile=0x7f070003;
        public static final int action_settings=0x7f070004;
        public static final int app_name=0x7f070005;
        public static final int auth_client_needs_enabling_title=0x7f07004a;
        public static final int auth_client_needs_installation_title=0x7f07004b;
        public static final int auth_client_needs_update_title=0x7f07004c;
        public static final int auth_client_play_services_err_notification_msg=0x7f07004d;
        public static final int auth_client_requested_by_msg=0x7f07004e;
        public static final int auth_client_using_bad_version_title=0x7f07004f;
        public static final int btnCreateUser=0x7f070006;
        public static final int btnLoginExistingUser=0x7f070007;
        public static final int btnLogout=0x7f070008;
        public static final int btnNo=0x7f070009;
        public static final int btnOk=0x7f07000a;
        public static final int btnSwitchUser=0x7f07000b;
        public static final int btnYes=0x7f07000c;
        public static final int common_google_play_services_enable_button=0x7f07000d;
        public static final int common_google_play_services_enable_text=0x7f07000e;
        public static final int common_google_play_services_enable_title=0x7f07000f;
        public static final int common_google_play_services_error_notification_requested_by_msg=0x7f070010;
        public static final int common_google_play_services_install_button=0x7f070011;
        public static final int common_google_play_services_install_text_phone=0x7f070012;
        public static final int common_google_play_services_install_text_tablet=0x7f070013;
        public static final int common_google_play_services_install_title=0x7f070014;
        public static final int common_google_play_services_invalid_account_text=0x7f070015;
        public static final int common_google_play_services_invalid_account_title=0x7f070016;
        public static final int common_google_play_services_needs_enabling_title=0x7f070017;
        public static final int common_google_play_services_network_error_text=0x7f070018;
        public static final int common_google_play_services_network_error_title=0x7f070019;
        public static final int common_google_play_services_notification_needs_installation_title=0x7f07001a;
        public static final int common_google_play_services_notification_needs_update_title=0x7f07001b;
        public static final int common_google_play_services_notification_ticker=0x7f07001c;
        public static final int common_google_play_services_unknown_issue=0x7f07001d;
        public static final int common_google_play_services_unsupported_date_text=0x7f07001e;
        public static final int common_google_play_services_unsupported_text=0x7f07001f;
        public static final int common_google_play_services_unsupported_title=0x7f070020;
        public static final int common_google_play_services_update_button=0x7f070021;
        public static final int common_google_play_services_update_text=0x7f070022;
        public static final int common_google_play_services_update_title=0x7f070023;
        public static final int common_signin_button_text=0x7f070024;
        public static final int common_signin_button_text_long=0x7f070025;
        public static final int create_user=0x7f070026;
        public static final int create_user_error_message=0x7f070027;
        public static final int create_user_error_title=0x7f070028;
        public static final int create_user_loading_title=0x7f070029;
        public static final int create_user_success_message=0x7f07002a;
        public static final int gravity_notification=0x7f07002b;
        public static final int gravity_notification_text=0x7f07002c;
        public static final int gravity_notification_title=0x7f07002d;
        public static final int hello_world=0x7f07002e;
        public static final int loading_existing_users_title=0x7f07002f;
        public static final int login=0x7f070030;
        public static final int login_fragment=0x7f070031;
        public static final int logout=0x7f070032;
        public static final int message_fragment=0x7f070033;
        public static final int notification_text=0x7f070034;
        public static final int notification_title=0x7f070035;
        public static final int please_wait_message=0x7f070036;
        public static final int pre_release_do_not_ship=0x7f070037;
        public static final int profile_email=0x7f070038;
        public static final int profile_name=0x7f070039;
        public static final int profile_phone=0x7f07003a;
        public static final int quit_app_message=0x7f07003b;
        public static final int quit_app_title=0x7f07003c;
        public static final int select_user=0x7f07003d;
        public static final int set_email=0x7f07003e;
        public static final int set_name=0x7f07003f;
        public static final int set_phone_number=0x7f070040;
        public static final int state_available=0x7f070041;
        public static final int state_busy=0x7f070042;
        public static final int submit_message=0x7f070043;
        public static final int title_activity_create_user=0x7f070044;
        public static final int title_activity_login_existing_user=0x7f070045;
        public static final int title_activity_main=0x7f070046;
        public static final int title_activity_message=0x7f070047;
        public static final int title_activity_profile=0x7f070048;
        public static final int wallet_buy_button_place_holder=0x7f070049;
    }
    public static final class style {
        public static final int Theme_IAPTheme=0x7f080000;
        public static final int WalletFragmentDefaultButtonTextAppearance=0x7f080001;
        public static final int WalletFragmentDefaultDetailsHeaderTextAppearance=0x7f080002;
        public static final int WalletFragmentDefaultDetailsTextAppearance=0x7f080003;
        public static final int WalletFragmentDefaultStyle=0x7f080004;
    }
    public static final class styleable {
        /** Attributes that can be used with a AdsAttrs.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #AdsAttrs_adSize dk.itu.pervasive.common.test:adSize}</code></td><td>
    The size of the ad.</td></tr>
           <tr><td><code>{@link #AdsAttrs_adSizes dk.itu.pervasive.common.test:adSizes}</code></td><td>
    A comma-separated list of the supported ad sizes.</td></tr>
           <tr><td><code>{@link #AdsAttrs_adUnitId dk.itu.pervasive.common.test:adUnitId}</code></td><td> The ad unit ID.</td></tr>
           </table>
           @see #AdsAttrs_adSize
           @see #AdsAttrs_adSizes
           @see #AdsAttrs_adUnitId
         */
        public static final int[] AdsAttrs = {
            0x7f010000, 0x7f010001, 0x7f010002
        };
        /**
          <p>
          @attr description
          
    The size of the ad. It must be one of BANNER, FULL_BANNER, LEADERBOARD,
    MEDIUM_RECTANGLE, SMART_BANNER, WIDE_SKYSCRAPER, or
    &lt;width&gt;x&lt;height&gt;.
        


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:adSize
        */
        public static final int AdsAttrs_adSize = 0;
        /**
          <p>
          @attr description
          
    A comma-separated list of the supported ad sizes. The sizes must be one of
    BANNER, FULL_BANNER, LEADERBOARD, MEDIUM_RECTANGLE, SMART_BANNER,
    WIDE_SKYSCRAPER, or &lt;width&gt;x&lt;height&gt;.
        


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:adSizes
        */
        public static final int AdsAttrs_adSizes = 1;
        /**
          <p>
          @attr description
           The ad unit ID. 


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:adUnitId
        */
        public static final int AdsAttrs_adUnitId = 2;
        /** Attributes that can be used with a MapAttrs.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #MapAttrs_cameraBearing dk.itu.pervasive.common.test:cameraBearing}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraTargetLat dk.itu.pervasive.common.test:cameraTargetLat}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraTargetLng dk.itu.pervasive.common.test:cameraTargetLng}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraTilt dk.itu.pervasive.common.test:cameraTilt}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraZoom dk.itu.pervasive.common.test:cameraZoom}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_mapType dk.itu.pervasive.common.test:mapType}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiCompass dk.itu.pervasive.common.test:uiCompass}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiRotateGestures dk.itu.pervasive.common.test:uiRotateGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiScrollGestures dk.itu.pervasive.common.test:uiScrollGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiTiltGestures dk.itu.pervasive.common.test:uiTiltGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiZoomControls dk.itu.pervasive.common.test:uiZoomControls}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiZoomGestures dk.itu.pervasive.common.test:uiZoomGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_useViewLifecycle dk.itu.pervasive.common.test:useViewLifecycle}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_zOrderOnTop dk.itu.pervasive.common.test:zOrderOnTop}</code></td><td></td></tr>
           </table>
           @see #MapAttrs_cameraBearing
           @see #MapAttrs_cameraTargetLat
           @see #MapAttrs_cameraTargetLng
           @see #MapAttrs_cameraTilt
           @see #MapAttrs_cameraZoom
           @see #MapAttrs_mapType
           @see #MapAttrs_uiCompass
           @see #MapAttrs_uiRotateGestures
           @see #MapAttrs_uiScrollGestures
           @see #MapAttrs_uiTiltGestures
           @see #MapAttrs_uiZoomControls
           @see #MapAttrs_uiZoomGestures
           @see #MapAttrs_useViewLifecycle
           @see #MapAttrs_zOrderOnTop
         */
        public static final int[] MapAttrs = {
            0x7f010003, 0x7f010004, 0x7f010005, 0x7f010006,
            0x7f010007, 0x7f010008, 0x7f010009, 0x7f01000a,
            0x7f01000b, 0x7f01000c, 0x7f01000d, 0x7f01000e,
            0x7f01000f, 0x7f010010
        };
        /**
          <p>This symbol is the offset where the {@link dk.itu.pervasive.common.test.R.attr#cameraBearing}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name dk.itu.pervasive.common.test:cameraBearing
        */
        public static final int MapAttrs_cameraBearing = 1;
        /**
          <p>This symbol is the offset where the {@link dk.itu.pervasive.common.test.R.attr#cameraTargetLat}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name dk.itu.pervasive.common.test:cameraTargetLat
        */
        public static final int MapAttrs_cameraTargetLat = 2;
        /**
          <p>This symbol is the offset where the {@link dk.itu.pervasive.common.test.R.attr#cameraTargetLng}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name dk.itu.pervasive.common.test:cameraTargetLng
        */
        public static final int MapAttrs_cameraTargetLng = 3;
        /**
          <p>This symbol is the offset where the {@link dk.itu.pervasive.common.test.R.attr#cameraTilt}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name dk.itu.pervasive.common.test:cameraTilt
        */
        public static final int MapAttrs_cameraTilt = 4;
        /**
          <p>This symbol is the offset where the {@link dk.itu.pervasive.common.test.R.attr#cameraZoom}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name dk.itu.pervasive.common.test:cameraZoom
        */
        public static final int MapAttrs_cameraZoom = 5;
        /**
          <p>This symbol is the offset where the {@link dk.itu.pervasive.common.test.R.attr#mapType}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>normal</code></td><td>1</td><td></td></tr>
<tr><td><code>satellite</code></td><td>2</td><td></td></tr>
<tr><td><code>terrain</code></td><td>3</td><td></td></tr>
<tr><td><code>hybrid</code></td><td>4</td><td></td></tr>
</table>
          @attr name dk.itu.pervasive.common.test:mapType
        */
        public static final int MapAttrs_mapType = 0;
        /**
          <p>This symbol is the offset where the {@link dk.itu.pervasive.common.test.R.attr#uiCompass}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name dk.itu.pervasive.common.test:uiCompass
        */
        public static final int MapAttrs_uiCompass = 6;
        /**
          <p>This symbol is the offset where the {@link dk.itu.pervasive.common.test.R.attr#uiRotateGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name dk.itu.pervasive.common.test:uiRotateGestures
        */
        public static final int MapAttrs_uiRotateGestures = 7;
        /**
          <p>This symbol is the offset where the {@link dk.itu.pervasive.common.test.R.attr#uiScrollGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name dk.itu.pervasive.common.test:uiScrollGestures
        */
        public static final int MapAttrs_uiScrollGestures = 8;
        /**
          <p>This symbol is the offset where the {@link dk.itu.pervasive.common.test.R.attr#uiTiltGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name dk.itu.pervasive.common.test:uiTiltGestures
        */
        public static final int MapAttrs_uiTiltGestures = 9;
        /**
          <p>This symbol is the offset where the {@link dk.itu.pervasive.common.test.R.attr#uiZoomControls}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name dk.itu.pervasive.common.test:uiZoomControls
        */
        public static final int MapAttrs_uiZoomControls = 10;
        /**
          <p>This symbol is the offset where the {@link dk.itu.pervasive.common.test.R.attr#uiZoomGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name dk.itu.pervasive.common.test:uiZoomGestures
        */
        public static final int MapAttrs_uiZoomGestures = 11;
        /**
          <p>This symbol is the offset where the {@link dk.itu.pervasive.common.test.R.attr#useViewLifecycle}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name dk.itu.pervasive.common.test:useViewLifecycle
        */
        public static final int MapAttrs_useViewLifecycle = 12;
        /**
          <p>This symbol is the offset where the {@link dk.itu.pervasive.common.test.R.attr#zOrderOnTop}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name dk.itu.pervasive.common.test:zOrderOnTop
        */
        public static final int MapAttrs_zOrderOnTop = 13;
        /** Attributes that can be used with a WalletFragmentOptions.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #WalletFragmentOptions_environment dk.itu.pervasive.common.test:environment}</code></td><td> Google Wallet environment to use </td></tr>
           <tr><td><code>{@link #WalletFragmentOptions_fragmentMode dk.itu.pervasive.common.test:fragmentMode}</code></td><td> Fragment mode </td></tr>
           <tr><td><code>{@link #WalletFragmentOptions_fragmentStyle dk.itu.pervasive.common.test:fragmentStyle}</code></td><td> A style resource specifing attributes to customize the look and feel of WalletFragment </td></tr>
           <tr><td><code>{@link #WalletFragmentOptions_theme dk.itu.pervasive.common.test:theme}</code></td><td> Theme to be used for the Wallet selector </td></tr>
           </table>
           @see #WalletFragmentOptions_environment
           @see #WalletFragmentOptions_fragmentMode
           @see #WalletFragmentOptions_fragmentStyle
           @see #WalletFragmentOptions_theme
         */
        public static final int[] WalletFragmentOptions = {
            0x7f010011, 0x7f010012, 0x7f010013, 0x7f010014
        };
        /**
          <p>
          @attr description
           Google Wallet environment to use 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>production</code></td><td>1</td><td></td></tr>
<tr><td><code>sandbox</code></td><td>0</td><td></td></tr>
<tr><td><code>strict_sandbox</code></td><td>2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:environment
        */
        public static final int WalletFragmentOptions_environment = 1;
        /**
          <p>
          @attr description
           Fragment mode 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>buyButton</code></td><td>1</td><td></td></tr>
<tr><td><code>selectionDetails</code></td><td>2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:fragmentMode
        */
        public static final int WalletFragmentOptions_fragmentMode = 3;
        /**
          <p>
          @attr description
           A style resource specifing attributes to customize the look and feel of WalletFragment 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:fragmentStyle
        */
        public static final int WalletFragmentOptions_fragmentStyle = 2;
        /**
          <p>
          @attr description
           Theme to be used for the Wallet selector 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>holo_dark</code></td><td>0</td><td></td></tr>
<tr><td><code>holo_light</code></td><td>1</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:theme
        */
        public static final int WalletFragmentOptions_theme = 0;
        /** Attributes that can be used with a WalletFragmentStyle.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #WalletFragmentStyle_buyButtonAppearance dk.itu.pervasive.common.test:buyButtonAppearance}</code></td><td> Appearance of the buy button.</td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_buyButtonHeight dk.itu.pervasive.common.test:buyButtonHeight}</code></td><td>
             Height of the buy button.</td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_buyButtonText dk.itu.pervasive.common.test:buyButtonText}</code></td><td> Text on the buy button.</td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_buyButtonWidth dk.itu.pervasive.common.test:buyButtonWidth}</code></td><td>
             Width of the buy button.</td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsBackground dk.itu.pervasive.common.test:maskedWalletDetailsBackground}</code></td><td> Masked wallet details background </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsButtonBackground dk.itu.pervasive.common.test:maskedWalletDetailsButtonBackground}</code></td><td> "Change" button background in masked wallet details view </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance dk.itu.pervasive.common.test:maskedWalletDetailsButtonTextAppearance}</code></td><td> TextAppearance for the "Change" button in masked wallet details view </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance dk.itu.pervasive.common.test:maskedWalletDetailsHeaderTextAppearance}</code></td><td> TextAppearance for headers describing masked wallet details </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsLogoImageType dk.itu.pervasive.common.test:maskedWalletDetailsLogoImageType}</code></td><td> Type of the wallet logo image in masked wallet details view </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsLogoTextColor dk.itu.pervasive.common.test:maskedWalletDetailsLogoTextColor}</code></td><td> Color of the Google Wallet logo text in masked wallet details view </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsTextAppearance dk.itu.pervasive.common.test:maskedWalletDetailsTextAppearance}</code></td><td> TextAppearance for masked wallet details </td></tr>
           </table>
           @see #WalletFragmentStyle_buyButtonAppearance
           @see #WalletFragmentStyle_buyButtonHeight
           @see #WalletFragmentStyle_buyButtonText
           @see #WalletFragmentStyle_buyButtonWidth
           @see #WalletFragmentStyle_maskedWalletDetailsBackground
           @see #WalletFragmentStyle_maskedWalletDetailsButtonBackground
           @see #WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance
           @see #WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance
           @see #WalletFragmentStyle_maskedWalletDetailsLogoImageType
           @see #WalletFragmentStyle_maskedWalletDetailsLogoTextColor
           @see #WalletFragmentStyle_maskedWalletDetailsTextAppearance
         */
        public static final int[] WalletFragmentStyle = {
            0x7f010015, 0x7f010016, 0x7f010017, 0x7f010018,
            0x7f010019, 0x7f01001a, 0x7f01001b, 0x7f01001c,
            0x7f01001d, 0x7f01001e, 0x7f01001f
        };
        /**
          <p>
          @attr description
           Appearance of the buy button. Must be one of "classic", "grayscale" and "monochrome" 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>classic</code></td><td>1</td><td></td></tr>
<tr><td><code>grayscale</code></td><td>2</td><td></td></tr>
<tr><td><code>monochrome</code></td><td>3</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:buyButtonAppearance
        */
        public static final int WalletFragmentStyle_buyButtonAppearance = 3;
        /**
          <p>
          @attr description
          
             Height of the buy button. This includes an 8dp padding (4dp on each side) used for
             pressed and focused states of the button. The value can be a specific height, e.g.
             "48dp", or special values "match_parent" and "wrap_content".
        


          <p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>match_parent</code></td><td>-1</td><td></td></tr>
<tr><td><code>wrap_content</code></td><td>-2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:buyButtonHeight
        */
        public static final int WalletFragmentStyle_buyButtonHeight = 0;
        /**
          <p>
          @attr description
           Text on the buy button. Must be one of "buy_with_google", "buy_now" and "book_now" 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>buy_with_google</code></td><td>1</td><td></td></tr>
<tr><td><code>buy_now</code></td><td>2</td><td></td></tr>
<tr><td><code>book_now</code></td><td>3</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:buyButtonText
        */
        public static final int WalletFragmentStyle_buyButtonText = 2;
        /**
          <p>
          @attr description
          
             Width of the buy button. This includes an 8dp padding (4dp on each side) used for
             pressed and focused states of the button. The value can be a specific width, e.g.
             "300dp", or special values "match_parent" and "wrap_content".
        


          <p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>match_parent</code></td><td>-1</td><td></td></tr>
<tr><td><code>wrap_content</code></td><td>-2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:buyButtonWidth
        */
        public static final int WalletFragmentStyle_buyButtonWidth = 1;
        /**
          <p>
          @attr description
           Masked wallet details background 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:maskedWalletDetailsBackground
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsBackground = 6;
        /**
          <p>
          @attr description
           "Change" button background in masked wallet details view 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:maskedWalletDetailsButtonBackground
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsButtonBackground = 8;
        /**
          <p>
          @attr description
           TextAppearance for the "Change" button in masked wallet details view 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:maskedWalletDetailsButtonTextAppearance
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance = 7;
        /**
          <p>
          @attr description
           TextAppearance for headers describing masked wallet details 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:maskedWalletDetailsHeaderTextAppearance
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance = 5;
        /**
          <p>
          @attr description
           Type of the wallet logo image in masked wallet details view 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>classic</code></td><td>1</td><td></td></tr>
<tr><td><code>monochrome</code></td><td>2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:maskedWalletDetailsLogoImageType
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsLogoImageType = 10;
        /**
          <p>
          @attr description
           Color of the Google Wallet logo text in masked wallet details view 


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:maskedWalletDetailsLogoTextColor
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsLogoTextColor = 9;
        /**
          <p>
          @attr description
           TextAppearance for masked wallet details 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name dk.itu.pervasive.common.test:maskedWalletDetailsTextAppearance
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsTextAppearance = 4;
    };
}
